// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "000A 0010 0000 ABCD",
        "A000 1000 0000 ABCD", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "00FF 0102",
        "FF00 1020", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "text 0",
        "text 0", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "",
        "", 0, false);
}
