// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "10\n",
        "0\n", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "11\n",
        "0\n", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "101\n",
        "11\n", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "1234\n",
        "14\n", 0, false);
}

TEST_CASE("case_5", "[behavior]") {
    course_test::CheckTask(Task,
        "1001\n",
        "11\n", 0, false);
}

TEST_CASE("case_6", "[behavior]") {
    course_test::CheckTask(Task,
        "987654\n",
        "9764\n", 0, false);
}

TEST_CASE("case_7", "[behavior]") {
    course_test::CheckTask(Task,
        "112233\n",
        "1223\n", 0, false);
}

TEST_CASE("case_8", "[behavior]") {
    course_test::CheckTask(Task,
        "1234567890\n",
        "13456780\n", 0, false);
}
