// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0.10000000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.691268139166703L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.16250000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.6476728661384938L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.22500000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.5849253394183056L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.28749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.5047859064539626L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.34999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.4094384937772388L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.41249999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.3013848494685156L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.47499999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.183328834534128L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.53749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.058058624645092L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.59999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.9283342378052784L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
