// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0.20000000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.80471895621705014L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.26250000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.66875209847522932L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.32500000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.56196504832619976L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.38749999999999996L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.47401971509436774L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.44999999999999996L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.39925384810888587L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.51249999999999996L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.33422728398478696L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.57499999999999996L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.27669261909239334L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.63749999999999996L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.22510050097477796L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.69999999999999996L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.17833747196936622L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
