// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "0.001\n",
        "1.08944280084911 1.14743885062954\n", 0.001, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "0.00001\n",
        "1.08944280084911 1.14743885062954\n", 1e-05, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "0.0000001\n",
        "1.08944280084911 1.14743885062954\n", 1e-07, false);
}
