// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "16 17 20 77 78",
        "dix-sept vingt soixante-dix-sept", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "-17 -77",
        "moins dix-sept moins soixante-dix-sept", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "0 100",
        "", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "",
        "", 0, false);
}
