// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0.10000000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.2214027581601699L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.16250000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.3840306459807514L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.22500000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.5683121854901689L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.28749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.7771305269140383L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.34999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.0137527074704766L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.41249999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.2818807653293036L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.47499999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.585709659315846L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.53749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 2.9299929005337013L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.59999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 3.3201169227365472L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
