// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0.10000000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = -3.4567901234567895L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.16250000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = -3.8137669859656937L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.22500000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = -4.2455775234131101L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.28749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = -4.7768544167436131L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.34999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = -5.4437869822485201L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.41249999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = -6.301493888637391L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.47499999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = -7.4376417233560081L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.53749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = -8.9992695398100793L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.59999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = -11.249999999999998L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
