// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.20000000000000001L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.25L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.22222222222222221L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.5L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.25L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.75L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.2857142857142857L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(1L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.33333333333333331L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(1.25L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.40000000000000002L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(1.5L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.5L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(1.75L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.66666666666666663L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(2L);
    REQUIRE(std::isfinite(result));
    const long double expected = -1L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
