// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "1\n5\n",
        "1\n1 1\n0\n", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "1\n0\n",
        "1\n1 1\n0\n", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "2\n1 2\n3 4\n",
        "0\n2 2\n0 -1\n1 0\n", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "3\n4 1 4\n2 -3 2\n4 1 4\n",
        "0\n3 3\n0 -1 0\n1 0 1\n0 -1 0\n", 0, false);
}

TEST_CASE("case_5", "[behavior]") {
    course_test::CheckTask(Task,
        "3\n0 0 0\n0 0 0\n0 0 0\n",
        "1\n3 3\n0 0 0\n0 0 0\n0 0 0\n", 0, false);
}

TEST_CASE("case_6", "[behavior]") {
    course_test::CheckTask(Task,
        "3\n2 2 1\n2 2 1\n3 3 -1\n",
        "0\n3 3\n0 0 -2\n0 0 -2\n2 2 0\n", 0, false);
}

TEST_CASE("case_7", "[behavior]") {
    course_test::CheckTask(Task,
        "3\n0 2 -3\n-2 0 4\n3 -4 0\n",
        "0\n3 3\n0 4 -6\n-4 0 8\n6 -8 0\n", 0, false);
}
