// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "12 34 56",
        "10 11 3\n11 4 4", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "9 100 8",
        "1 1 1\n0 0 0\n0 0 0", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "123",
        "NONE", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "",
        "NONE", 0, false);
}
