// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0.10000000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.98503747361929428L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.16250000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.96065162326867892L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.22500000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.92502016549393939L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.28749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.87856278189785098L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.34999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.82182901788077289L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.41249999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.75549373369875716L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.47499999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.68035150526005261L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.53749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.59731001276007034L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.59999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.50738246220742567L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
