// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.0625L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.12516314295400599L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.125L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.25131442828090617L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.1875L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.37948962170490369L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.25L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.51082562376599072L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.3125L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.64662716492505246L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.375L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.78845736036427028L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.4375L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.93826963859293022L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.5L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.0986122886681098L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
