// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "11 12 1750 1751 8 0",
        "2", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "10 100 1000",
        "2", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "777 0012 2000",
        "2", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "",
        "0", 0, false);
}
