// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("Specification must be clarified", "[specification]") {
    FAIL("Шаблон CheckZone(Point) требует геометрическую область, но рисунок содержит рекуррентные формулы i, j, l. Не заданы область, критерий остановки и ожидаемый результат. Нужен полный текст задания; тест нельзя корректно составить по одному рисунку.");
}
