// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "1\n42\n",
        "42\n", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "1\n-7\n",
        "-7\n", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 16\n",
        "13 14 15 16 12 8 4 3 2 1 5 9 10 11 7 6\n", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "4\n-8 -7 -6 -5\n-4 -3 -2 -1\n0 1 2 3\n4 5 6 7\n",
        "4 5 6 7 3 -1 -5 -6 -7 -8 -4 0 1 2 -2 -3\n", 0, false);
}

TEST_CASE("case_5", "[behavior]") {
    course_test::CheckTask(Task,
        "4\n0 0 0 0\n0 0 0 0\n0 0 0 0\n0 0 0 0\n",
        "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n", 0, false);
}

TEST_CASE("case_6", "[behavior]") {
    course_test::CheckTask(Task,
        "4\n5 -2 5 0\n99 1 -7 99\n4 4 2 0\n-1 3 8 6\n",
        "-1 3 8 6 0 99 0 5 -2 5 99 4 4 2 -7 1\n", 0, false);
}
