// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "17 18 22 85 86",
        "siebzehn zwanzig siebenundsiebzig", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "-18 -85",
        "minus siebzehn minus siebenundsiebzig", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "0 888",
        "", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "",
        "", 0, false);
}
