// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0.62831853071795862L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.7237709894132196L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.94247779607693793L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.60040093439960263L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(1.2566370614359172L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.42768285738053891L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(1.5707963267948966L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.20561675835602833L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(1.8849555921538759L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.065797362673928994L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(2.1991148575128552L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.38655950570933306L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(2.5132741228718345L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.75666967075018399L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(2.8274333882308138L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.1761278577964815L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(3.1415926535897931L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.6449340668482262L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
