// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("Specification must be clarified", "[specification]") {
    FAIL("В условии используется латинский алфавит, но не заданы множества гласных 1/2 рода либо звонких/глухих/шипящих/свистящих согласных. Нужен точный состав множеств от преподавателя.");
}
