// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(-0.20000000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.3285040669720361L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(-0.13750000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.19275075228449381L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(-0.075000000000000011L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.090198267918148722L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(-0.012500000000000011L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.012895287985732726L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.049999999999999989L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.044016885416774468L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.11249999999999999L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.08359408636412409L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.17499999999999999L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.10773269980288203L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.23749999999999999L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.11750521929121284L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.29999999999999999L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.11332868530700327L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
