// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "abc\ndef",
        "abc def", 0, true);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "abc\n\ndef",
        "abc\n\ndef", 0, true);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "a!\nb",
        "a!\nb", 0, true);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "one\ntwo\nthree",
        "one two three", 0, true);
}

TEST_CASE("case_5", "[behavior]") {
    course_test::CheckTask(Task,
        "",
        "", 0, true);
}
