// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("Specification must be clarified", "[specification]") {
    FAIL("Не определены ширина записи и правила переноса блока нулей; у числового ввода ведущие нули не сохраняются. Нужны уточнение условия и примеры преподавателя.");
}
