// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("Specification must be clarified", "[specification]") {
    FAIL("Не определено, считать ли существительным любое слово с прописной буквы, как учитывать начало предложения и нужен ли словарь немецких существительных. Нужны уточнение условия и примеры преподавателя.");
}
