// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "",
        "0\n", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "123 !?",
        "0\n", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "a",
        "1\n", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "bbb",
        "0\n", 0, false);
}

TEST_CASE("case_5", "[behavior]") {
    course_test::CheckTask(Task,
        "aaa",
        "1\n", 0, false);
}

TEST_CASE("case_6", "[behavior]") {
    course_test::CheckTask(Task,
        "aeiou",
        "1\n", 0, false);
}

TEST_CASE("case_7", "[behavior]") {
    course_test::CheckTask(Task,
        "bcdfg",
        "0\n", 0, false);
}

TEST_CASE("case_8", "[behavior]") {
    course_test::CheckTask(Task,
        "aei aei",
        "1\n", 0, false);
}

TEST_CASE("case_9", "[behavior]") {
    course_test::CheckTask(Task,
        "abc cba",
        "1\n", 0, false);
}

TEST_CASE("case_10", "[behavior]") {
    course_test::CheckTask(Task,
        "ae ob",
        "0\n", 0, false);
}

TEST_CASE("case_11", "[behavior]") {
    course_test::CheckTask(Task,
        "aaa eee",
        "0\n", 0, false);
}

TEST_CASE("case_12", "[behavior]") {
    course_test::CheckTask(Task,
        "BbB aA",
        "0\n", 0, false);
}

TEST_CASE("case_13", "[behavior]") {
    course_test::CheckTask(Task,
        "Hello, WORLD!",
        "1\n", 0, false);
}

TEST_CASE("case_14", "[behavior]") {
    course_test::CheckTask(Task,
        "rhythm sky",
        "0\n", 0, false);
}

TEST_CASE("case_15", "[behavior]") {
    course_test::CheckTask(Task,
        "ab cd",
        "0\n", 0, false);
}

TEST_CASE("case_16", "[behavior]") {
    course_test::CheckTask(Task,
        "aei,AEI;aei",
        "1\n", 0, false);
}

TEST_CASE("case_17", "[behavior]") {
    course_test::CheckTask(Task,
        "AaB",
        "1\n", 0, false);
}
