// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "кот дом",
        "3", 1e-09, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "я люблю C",
        "2.3333333333333333", 1e-09, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "hello мир",
        "4", 1e-09, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "",
        "0", 1e-09, false);
}

TEST_CASE("case_5", "[behavior]") {
    course_test::CheckTask(Task,
        "ёж! а?",
        "1.5", 1e-09, false);
}
