// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0L);
    REQUIRE(std::isfinite(result));
    const long double expected = -1.6666666666666667L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.0625L);
    REQUIRE(std::isfinite(result));
    const long double expected = -1.747517730496454L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.125L);
    REQUIRE(std::isfinite(result));
    const long double expected = -1.8385093167701863L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.1875L);
    REQUIRE(std::isfinite(result));
    const long double expected = -1.9418803418803419L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.25L);
    REQUIRE(std::isfinite(result));
    const long double expected = -2.0606060606060606L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.3125L);
    REQUIRE(std::isfinite(result));
    const long double expected = -2.1987315010570825L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.375L);
    REQUIRE(std::isfinite(result));
    const long double expected = -2.361904761904762L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.4375L);
    REQUIRE(std::isfinite(result));
    const long double expected = -2.5582655826558267L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.5L);
    REQUIRE(std::isfinite(result));
    const long double expected = -2.7999999999999998L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
