// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "fsm.h"

TEST_CASE("Specification must be clarified", "[specification]") {
    FAIL("Не задан порог длины малобуквенного слова. Нужны уточнение условия и примеры преподавателя.");
}
