#!/usr/bin/env python3
"""Render Catch tests from explicit fixtures, without generating solutions."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GROUPS = {'bitsets', 'finite_state_machine', 'geometry', 'integers',
          'linerization', 'matrix', 'numerical_methods', 'taylor'}


def literal(text):
    return json.dumps(str(text), ensure_ascii=False)


def render(path):
    data = json.loads(path.read_text())
    group = path.parts[-4]
    header = 'fsm.h' if group == 'finite_state_machine' else 'solution.h'
    lines = ['// Generated by tools/render_tests.py from tests.json; edit the fixtures.',
             '#include "../../../../tests/support/task_check.h"',
             f'#include "{header}"', '']
    if data['kind'] == 'blocked':
        lines += ['TEST_CASE("Specification must be clarified", "[specification]") {',
                  f'    FAIL({literal(data["reason"])});', '}']
    else:
        for case in data['cases']:
            lines.append(f'TEST_CASE({literal(case["name"])}, "[behavior]") {{')
            if data['kind'] == 'function':
                lines += [f'    const long double result = Func({case["input"]}L);',
                          '    REQUIRE(std::isfinite(result));',
                          f'    const long double expected = {case["expected"]}L;',
                          f'    CHECK(std::fabs(result - expected) <= {data["tolerance"]}L *',
                          '          std::fmax(1.0L, std::fabs(expected)));']
            else:
                tolerance = float(case['input']) if data.get('tolerance_from_input') else data.get('tolerance', 0)
                exact = 'true' if data.get('comparison') == 'exact' else 'false'
                lines += ['    course_test::CheckTask(Task,',
                          f'        {literal(case["input"])},',
                          f'        {literal(case["expected"])}, {tolerance}, {exact});']
            lines += ['}', '']
    return '\n'.join(lines).rstrip() + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check freshness without writing')
    args = parser.parse_args()
    stale = []
    count = 0
    for path in sorted(ROOT.glob('tasks/*/tasks/*/tests.json')):
        if path.parts[-4] not in GROUPS:
            continue
        target = path.with_name('test.cpp')
        content = render(path)
        count += 1
        if args.check:
            if not target.exists() or target.read_text() != content:
                stale.append(str(target.relative_to(ROOT)))
        elif not target.exists() or target.read_text() != content:
            target.write_text(content)
    if stale:
        print('Stale generated tests:\n' + '\n'.join(stale))
        return 1
    print(f'{count} Catch test files {"verified" if args.check else "generated"}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
