// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0.62831853071795862L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.48121182505960353L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(1.0210176124166828L);
    REQUIRE(std::isfinite(result));
    const long double expected = 0.023020466337725334L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(1.4137166941154069L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.2615147473148508L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(1.806415775814131L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.45147927148777856L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(2.1991148575128552L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.57774365134321004L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(2.5918139392115793L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.65487945907761025L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(2.9845130209103035L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.69005975309009926L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(3.3772121026090276L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.68619150277840835L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(3.7699111843077517L);
    REQUIRE(std::isfinite(result));
    const long double expected = -0.64296539063832692L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
