// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "0\n",
        "0000\n", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "7\n",
        "0111\n", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "10\n",
        "0001 0000\n", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "11\n",
        "0001 0001\n", 0, false);
}

TEST_CASE("case_5", "[behavior]") {
    course_test::CheckTask(Task,
        "101\n",
        "0001 0000 0001\n", 0, false);
}

TEST_CASE("case_6", "[behavior]") {
    course_test::CheckTask(Task,
        "1234\n",
        "0001 0010 0011 0100\n", 0, false);
}

TEST_CASE("case_7", "[behavior]") {
    course_test::CheckTask(Task,
        "1001\n",
        "0001 0000 0000 0001\n", 0, false);
}

TEST_CASE("case_8", "[behavior]") {
    course_test::CheckTask(Task,
        "987654\n",
        "1001 1000 0111 0110 0101 0100\n", 0, false);
}

TEST_CASE("case_9", "[behavior]") {
    course_test::CheckTask(Task,
        "112233\n",
        "0001 0001 0010 0010 0011 0011\n", 0, false);
}

TEST_CASE("case_10", "[behavior]") {
    course_test::CheckTask(Task,
        "1234567890\n",
        "0001 0010 0011 0100 0101 0110 0111 1000 1001 0000\n", 0, false);
}
