// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    const long double result = Func(0.10000000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.0050041680558035L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_2", "[behavior]") {
    const long double result = Func(0.16250000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.0132322043370443L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_3", "[behavior]") {
    const long double result = Func(0.22500000000000001L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.0254194674756207L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_4", "[behavior]") {
    const long double result = Func(0.28749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.0416135794670922L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_5", "[behavior]") {
    const long double result = Func(0.34999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.0618778191559852L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_6", "[behavior]") {
    const long double result = Func(0.41249999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.0862913694992533L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_7", "[behavior]") {
    const long double result = Func(0.47499999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.1149496269754013L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_8", "[behavior]") {
    const long double result = Func(0.53749999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.1479645743483L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}

TEST_CASE("case_9", "[behavior]") {
    const long double result = Func(0.59999999999999998L);
    REQUIRE(std::isfinite(result));
    const long double expected = 1.1854652182422676L;
    CHECK(std::fabs(result - expected) <= 1e-10L *
          std::fmax(1.0L, std::fabs(expected)));
}
