// Generated by tools/render_tests.py from tests.json; edit the fixtures.
#include "../../../../tests/support/task_check.h"
#include "solution.h"

TEST_CASE("case_1", "[behavior]") {
    course_test::CheckTask(Task,
        "0\n",
        "00\n", 0, false);
}

TEST_CASE("case_2", "[behavior]") {
    course_test::CheckTask(Task,
        "7\n",
        "07\n", 0, false);
}

TEST_CASE("case_3", "[behavior]") {
    course_test::CheckTask(Task,
        "10\n",
        "01 00\n", 0, false);
}

TEST_CASE("case_4", "[behavior]") {
    course_test::CheckTask(Task,
        "11\n",
        "01 01\n", 0, false);
}

TEST_CASE("case_5", "[behavior]") {
    course_test::CheckTask(Task,
        "101\n",
        "01 00 01\n", 0, false);
}

TEST_CASE("case_6", "[behavior]") {
    course_test::CheckTask(Task,
        "1234\n",
        "01 02 03 04\n", 0, false);
}

TEST_CASE("case_7", "[behavior]") {
    course_test::CheckTask(Task,
        "1001\n",
        "01 00 00 01\n", 0, false);
}

TEST_CASE("case_8", "[behavior]") {
    course_test::CheckTask(Task,
        "987654\n",
        "11 10 07 06 05 04\n", 0, false);
}

TEST_CASE("case_9", "[behavior]") {
    course_test::CheckTask(Task,
        "112233\n",
        "01 01 02 02 03 03\n", 0, false);
}

TEST_CASE("case_10", "[behavior]") {
    course_test::CheckTask(Task,
        "1234567890\n",
        "01 02 03 04 05 06 07 10 11 00\n", 0, false);
}
